### ISSUE TITLE
about train sparisity

### ISSUE THREAD

**Issue by monsterlyg** [ZJU-lishuang/yolov5-v4#1]
请教一个问题，稀疏训练的时候，添加的是cfg_model的bn的grad惩罚，可是loss反传用的是yml形式定义的model，这个不需要一致吗？  bn_module.weight.grad.data.add_(s * torch.sign(bn_module.weight.data))

**Comment by ZJU-lishuang** [comment]
在寄存器地址上数据的位置相同，只是使用了两种不同的网络解析方式。
