### ISSUE TITLE
def copy_weight_v4(modelyolov5,model):？

### ISSUE THREAD

**Issue by sbbug** [ZJU-lishuang/yolov5-v4#2]
你好，请问你代码中的：
def copy_weight_v4(modelyolov5,model):
这个方法主要作用是什么，为什么要copy呢，直接在原模型上不可以稀疏化BN层系数吗？
还有虽然做了拷贝，也是浅拷贝，底层数据仍是共享的，不知我理解可对？

**Comment by ZJU-lishuang** [comment]
在原模型上也可以进行稀疏化BN层系数。
cfg和yaml模型是等价的，是浅拷贝。
cfg网络是一层一层搭建的，方便剪枝，所以copy转换了一下
