### ISSUE TITLE
靓仔你好，请问下用原yolov5训练好的模型再继续用您项目里的train.py训练，精度从85%到60%是怎么回事呀？

### ISSUE THREAD

**Issue by OneCassie** [ZJU-lishuang/yolov5-v4#4]
精度一直在60%上不去了，数据集是人脸数据集widerface。

**Comment by ZJU-lishuang** [comment]
你看看是不是计算损失函数的问题,把[compute_loss_eiou](https://github.com/ZJU-lishuang/yolov5-v4/blob/main/train.py#L294)改回[compute_loss](https://github.com/ZJU-lishuang/yolov5-v4/blob/main/train.py#L293)

**Comment by ZJU-lishuang** [comment]
yolov5训练的其它流程应该没变，可以和原版比对
