### ISSUE TITLE
我这边实验发现 torch.cuda.amp 单精度训练貌似不支持稀疏化训练，你这边也是这种情况吗？

### ISSUE THREAD

**Issue by xuanyuyt** [ZJU-lishuang/yolov5-v4#6]
如题，我这边实验发现 torch.cuda.amp 单精度训练貌似不支持稀疏化训练，你这边也是这种情况吗？

**Comment by ZJU-lishuang** [comment]
问题应该是自动混合精度和稀疏化的参数更新未一致同步。我这边也是这种情况，目前暂时没打算进一步研究解决方案使torch.cuda.amp在稀疏化训练中可行

**Comment by xinxin12345** [comment]
> 问题应该是自动混合精度和稀疏化的参数更新未一致同步。我这边也是这种情况，目前暂时没打算进一步研究解决方案使torch.cuda.amp在稀疏化训练中可行

请问这个应该怎么解决呢，目前没有思路，不知您是否能提供一些思路呢

**Comment by ZJU-lishuang** [comment]
BN层参数稀疏化训练更新在amp中好像失效了，可以看下这是怎么回事
